# Generated by Django 4.0.4 on 2022-04-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_number_2',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
    ]
