# Generated by Django 4.0.4 on 2022-04-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_phone_number_2_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
