# Generated by Django 4.0.4 on 2022-04-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_appartment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
