# Generated by Django 4.0.4 on 2022-04-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('date_Check_In', models.DateField(blank=True, null=True)),
                ('date_Check_Out', models.DateField(blank=True, null=True)),
                ('adult', models.IntegerField(blank=True, default=0, null=True)),
                ('children', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('appartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appart_bk', to='rooms.appartment')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_client_bk', to='account.client')),
            ],
        ),
    ]
