# Generated by Django 4.0.4 on 2022-04-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
